VERSION = {"New International Version": "NIV",
           "King James Version": "KJV"}

BOOK = {"Genesis": "ge",
        "Exodus": "exo",
        "Leviticus": "lev",
        "Numbers": "num",
        "Deuteronomy": "deu",
        "Joshua": "josh",
        "Judges": "jdgs",
        "Ruth": "ruth",
        "1 Samuel": "1sm",
        "2 Samuel": "2sm",
        "1 Kings": "1ki",
        "2 Kings": "2ki",
        "1 Chronicles": "1chr",
        "2 Chronicles": "2chr",
        "Ezra": "ezra",
        "Nehemiah": "neh",
        "Esther": "est",
        "Job": "job",
        "Psalms": "psa",
        "Proverbs": "prv",
        "Ecclesiastes": "eccl",
        "Songs": "ssol",
        "Isaiah": "isa",
        "Jeremiah": "jer",
        "Lamentations": "lam",
        "Ezekiel": "eze",
        "Daniel": "dan",
        "Hosea": "hos",
        "Joel": "joel",
        "Amos": "amos",
        "Obadiah": "obad",
        "Jonah": "jonah",
        "Micah": "mic",
        "Nahum": "nahum",
        "Habakkuk": "hab",
        "Zephaniah": "zep",
        "Haggai": "hag",
        "Zechariah": "zep",
        "Malachi": "mal",
        "Matthew": "mat",
        "Mark": "mark",
        "Luke": "luke",
        "John": "john",
        "Acts": "acts",
        "Romans": "rom",
        "1 Corinthians": "1cor",
        "2 Corinthians": "2cor",
        "Galatians": "gal",
        "Ephesians": "eph",
        "Philippians": "phi",
        "Colossians": "col",
        "1 Thessalonians": "1th",
        "2 Thessalonians": "2th",
        "1 Timothy": "1tim",
        "2 Timothy": "2tim",
        "Titus": "titus",
        "Philemon": "phmn",
        "Hebrews": "heb",
        "James": "jas",
        "1 Peter": "1pet",
        "2 Peter": "2pet",
        "1 John": "1jn",
        "2 John": "2jn",
        "3 John": "3jn",
        "Jude": "jude",
        "Revelation": "rev"}
